#this is big heading

##this is small heading

In [1]:
import numpy as np
#import is a keyword which is used to import all dependencies
#as is a keyword to provide alias name for your library


In [2]:
# list - it is advanced data type which is used to store list of elements
#it is denoted by using square brackets
#each element is separated by comma
#it allows both homogeneous and hetrogeneous elements
#list is mutable

In [3]:
a1 = [1,2,3,4,5]
print(len(a1))

5


In [4]:
list1 = [10,20,30,40,50]
print(list1)

[10, 20, 30, 40, 50]


In [5]:
x = list(range(10))
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
print(type(x))

<class 'list'>


In [7]:
y = tuple(range(1,11))
print(y)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [8]:
x1 = [10,10.1,2+10j,False,'sravani']
print(type(x1))

<class 'list'>


#creating numpy array, using list

In [9]:
list1 = [10,20,30,40,50]
arr1 = np.array(list1)
print(arr1)

[10 20 30 40 50]


## create a numpy arrays using list and store float value

In [10]:
list2 = [10,20,30,40,50]
arr2 = np.array(list2,dtype=float)
print(arr2)

[10. 20. 30. 40. 50.]


## indexing the elements

In [11]:
a1 = [10,20,30,40,50]
print(a1[-1])

50


# order of datatypes

In [12]:
list3 = [10,10.1,2+10j,False,'sravani']
arr4 = np.array(list3)
print(arr4)

['10' '10.1' '(2+10j)' 'False' 'sravani']


In [13]:
d1 = {"age":"25","name":"sai"}
print(d1)

{'age': '25', 'name': 'sai'}


## generating the elements

In [14]:
r1 = list(range(0,10))
print(r1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
r1 = list(range(0,10,3))
print(r1)

[0, 3, 6, 9]


In [16]:
r1 = list(range(0,10,3.5))
print(r1)

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
arr5 = np.arange(0,10,3.5)
print(arr5)

In [ ]:
arr6 = np.arange(0,10,3.5,dtype=int)
print(arr6)

In [ ]:
arr6 = np.arange(0,10,2,dtype=float)
print(arr6)


In [ ]:
arr6 = np.arange(0,10,0.5,dtype=int)
print(arr6)

## creating 2d array using nested list

In [17]:
list7 = [[10,20,30],[40,50,60]]
arr7 = np.array(list7)
print(arr7)

[[10 20 30]
 [40 50 60]]


In [18]:
print(len(arr7))
print(arr7.ndim)
print(arr7.shape)
print(arr7.size)

2
2
(2, 3)
6


In [ ]:
class A:
    def_init_(self):
    self.x1=100
    self.y1=20
a1 = A()
print(a1.x1)

In [ ]:
arr8=np.arange(1,10).reshape(3,3)
print(arr8)
print(arr8.ndim)

In [ ]:
arr9=np.arange(1,10).reshape(3,3)
print(arr9)
print(arr9.ndim)

In [ ]:
arr10=np.array(1,2,3,4,5

## creating array using ndmin

In [ ]:
arr10=np.array([1,2,3,4],ndmin=5)
print(arr10)

## creating flattened the array

In [ ]:
arr11=np.array([[1,2,],[3,4],[5,6]])
print(arr11)

In [ ]:
print(arr11.flatten())

In [ ]:
print(10+5)
print([10],[5])

## arthematic oparator

In [ ]:
z1 = np.arange(1,5).reshape(2,2)
z2 = np.arange(1,5).reshape(2,2)
print(z1)
print(z2)

In [ ]:
print(z1+4)

In [ ]:
print(z1**4)

In [ ]:
print(z1*4)

In [ ]:
print(z1.flatten())

In [ ]:
print(np.repeat(z1,4))

In [ ]:
#print([10,20,30]+3)
#print([10,20,30]-3)
print([10,20,30]*3)
#print([10,20,30]//3)

## accessing array elements 

In [ ]:
arr1 = np.arange(1,21).reshape(5,4)
print(arr1)

In [ ]:
print(arr1[0])

In [ ]:
print(arr1[-1])

In [ ]:
print(arr1[0][: : -1])

In [ ]:
print(arr1[-1: : -1])

In [ ]:
print(arr1[0][0:2])
print(arr1[1][0:2])

In [ ]:
print(arr1[0],[1],[2],[3],[4][0:2])

In [ ]:
print(arr1[0:5,0:2])

In [ ]:
print(arr1[0:5,-1:6])

In [ ]:
print(arr1[:,-1])

In [ ]:
print(arr1[::-1 ,::-1])

## matrices

In [ ]:
a1 = np.arange([1,2],[3,4])
print(a1)

In [ ]:
b1 = np.arange(1,3).reshape(1,2)
b2 = np.arange(1,3).reshape(2,1)

In [ ]:
print(b1)
print(b2)

In [ ]:
print(b1*b2)

In [ ]:
m1 = np.ones((3,3),dtype=int)
print(m1*4)

In [ ]:
m2 = np.eye(3,dtype=int)
print(m2)

## aggregate funtion

In [ ]:
arr1 = np.random.randint(1,50,10)
print(arr1)

In [ ]:
print(np.min(arr1))
print(np.argmin(arr1))
print(np.mean(arr1))
print(np.median(arr1))