In [1]:
list=[1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [2]:
x=range(10)
print(x)

range(0, 10)


In [4]:

x = list(range(4))
print(x)

TypeError: 'list' object is not callable

In [ ]:
x = list(range(4))
print(x)

In [5]:
del list

In [6]:
x = list(range(4))
print(x)

[0, 1, 2, 3]


In [7]:
x = tuple(range(4))
print(x)

(0, 1, 2, 3)


In [8]:
# list is converted into numpy 


In [21]:
import numpy as np
list1=[11,12,13,14,15]
arr=np.array(list1)
print(arr)

[11 12 13 14 15]


In [27]:
tuple1 = (21,22,23,24,25)
arr2 = np.array(tuple1)
print(arr2)
print(type(arr2))

[21 22 23 24 25]
<class 'numpy.ndarray'>


In [23]:
print(len(list1))

5


In [25]:
list1[0]=10
print(list1)

[10, 12, 13, 14, 15]


In [33]:
tuple2=(1,2,3,4,5)
arr3=np.array(tuple2,dtype=int)
arr4=np.array(tuple2,dtype=float)
arr5=np.array(tuple2,dtype=complex)
arr6=np.array(tuple2,dtype=bool)
print(arr3,arr4,arr5,arr6)

[1 2 3 4 5] [1. 2. 3. 4. 5.] [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j] [ True  True  True  True  True]


In [36]:
del list

In [37]:
r=list(range(0,10,2))
print(r)

[0, 2, 4, 6, 8]


In [53]:
r1=np.linspace(0,10,10)
print(r1)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [54]:
r2=list(range(0,10,10))
print(r2)

[0]


In [55]:
r3=np.linspace(1,50,49)
print(r3)

[ 1.          2.02083333  3.04166667  4.0625      5.08333333  6.10416667
  7.125       8.14583333  9.16666667 10.1875     11.20833333 12.22916667
 13.25       14.27083333 15.29166667 16.3125     17.33333333 18.35416667
 19.375      20.39583333 21.41666667 22.4375     23.45833333 24.47916667
 25.5        26.52083333 27.54166667 28.5625     29.58333333 30.60416667
 31.625      32.64583333 33.66666667 34.6875     35.70833333 36.72916667
 37.75       38.77083333 39.79166667 40.8125     41.83333333 42.85416667
 43.875      44.89583333 45.91666667 46.9375     47.95833333 48.97916667
 50.        ]


In [62]:
list2=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr7=np.array(list2)
print(arr7)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [63]:
print(arr7.shape)
print(arr7.size)
print(arr7.ndim)
print(arr7.dtype)

(4, 5)
20
2
int64


In [66]:
arr8=np.arange(1,10).reshape(3,3)
print(arr8)
print(arr8.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [70]:
arr8=np.array[1,2,3,4,5]
print(arr8.ndmin==2)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [72]:
arr8 = np.array([1, 2, 3], ndmin=8)
print(arr8)

[[[[[[[[1 2 3]]]]]]]]


In [80]:
arr9=np.arange(1,10).reshape(3,3)
print(arr9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
